import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { fetchPlaces, fetchPlaceMeta, fetchAllPlacesByCity } from "../utils/placeApi";
import ThemeToggle from "../components/ThemeToggle";
import BrandMark from "../components/BrandMark";
import { getUser, getServerSession, setLoggedIn, logoutSession, fetchGuidePackages, removeGuidePackage, createGuidePackage, fetchBookings, getGuidePlaceAvailability, saveGuidePlaceAvailability, removeGuidePlaceAvailability, fetchGuideAvailability, createGuideAvailability, removeGuideAvailability, fetchGuideRequests, respondGuideRequest, fetchNotifications, markNotificationRead, daysBetween, formatDate, formatDateTime, authHeaders } from "../utils";

export default function GuideDashboard(){
 const [user,setUser]=useState(getUser()||{name:"Local Guide",email:"",role:"guide",verificationStatus:"Pending"}); const nav=useNavigate(); const [packages,setPackages]=useState([]); const [destinations,setDestinations]=useState([]); const [bookings,setBookings]=useState([]); const [placeAvailability,setPlaceAvailability]=useState([]); const [requests,setRequests]=useState([]); const [notifications,setNotifications]=useState([]); const [showCreate,setShowCreate]=useState(false); const [editingPackage,setEditingPackage]=useState(null); const [showPlace,setShowPlace]=useState(false); const [showRequests,setShowRequests]=useState(false); const [notice,setNotice]=useState(""); const [showNotifications,setShowNotifications]=useState(false); const [highlightBookingId,setHighlightBookingId]=useState("");
 useEffect(()=>{fetchPlaces({page:1,pageSize:48}).then(setDestinations)},[]);
 const refresh=async()=>{
   const latest=await getServerSession();
   const current=latest?.role==="guide" ? latest : user;
   if(latest?.role==="guide") setUser(latest);
   const verifiedNow=(current?.verificationStatus||"Pending")==="Verified";
   if(verifiedNow){
     setPackages(await fetchGuidePackages(current.email));
     setPlaceAvailability(await fetchGuideAvailability({guideEmail:current.email}));
   } else {
     // Never surface cached/local package or availability records while the
     // Admin verification gate is pending/rejected/suspended.
     setPackages([]);
     setPlaceAvailability([]);
   }
   setBookings(await fetchBookings({guideEmail:current.email}));
   setRequests(await fetchGuideRequests({guideEmail:current.email}));
   setNotifications(await fetchNotifications());
 };
 useEffect(()=>{refresh(); const onChange=()=>refresh(); window.addEventListener("stg-data-change",onChange); const timer=setInterval(refresh,5000); window.addEventListener("focus",refresh); return()=>{window.removeEventListener("stg-data-change",onChange);window.removeEventListener("focus",refresh);clearInterval(timer)}},[]);
 const logout=async()=>{await logoutSession();setLoggedIn(false);nav("/")};
 const activeBookings=bookings.filter(b=>!['Cancelled','Rejected','Not Available'].includes(b.status)).length;
 const openBookingFromNotification=async(notification)=>{
   try{if(!notification.read) await markNotificationRead(notification.id);}catch{}
   setShowNotifications(false);
   await refresh();
   const bookingId=notification.bookingId||notification.requestId;
   if(bookingId){
     setHighlightBookingId(String(bookingId));
     setTimeout(()=>document.getElementById("bookings")?.scrollIntoView({behavior:"smooth",block:"center"}),80);
     setTimeout(()=>setHighlightBookingId(""),3500);
   }
 };
 const guideStatus=user.verificationStatus||"Pending";
 const verified=guideStatus==="Verified";
 const latestVerification=Array.isArray(user.verificationHistory)
   ? user.verificationHistory.find(x=>x.status===guideStatus)
   : null;
 const rejectionReason=(guideStatus==="Rejected" || guideStatus==="Changes Required")
   ? String(latestVerification?.note || "").trim()
   : "";
 const statusNote=guideStatus==="Rejected"
   ? "The Admin rejected your Local Guide verification. Review the reason below and update your details before resubmitting."
   : guideStatus==="Changes Required"
   ? "The Admin requested changes to your Local Guide verification details."
   : guideStatus==="Pending"
   ? "Your Local Guide details were submitted and are waiting for Admin verification."
   : guideStatus==="Verified"
   ? "Your Local Guide account is verified. Package and availability features are active."
   : guideStatus==="Suspended"
   ? "Your Local Guide access is currently suspended by STG Admin."
   : "Your Local Guide verification is currently under review.";
 return <main className="guide-page">
  <aside className="guide-sidebar"><div className="guide-brand"><BrandMark className="guide-brand-mark"/><div><strong>Smart Travel Guide</strong><small>Guide · Share · Inspire</small></div></div><nav>
   <a className="active" href="#top"><i className="bi bi-house-door-fill"/>Dashboard</a><a href="#packages"><i className="bi bi-briefcase"/>My Packages</a><a href="#availability"><i className="bi bi-calendar-check"/>Place Availability</a><a href="#bookings"><i className="bi bi-clipboard-check"/>Bookings</a><a href="#profile" onClick={(e)=>{e.preventDefault();nav("/guide/profile");}}><i className="bi bi-person"/>My Profile</a><a href="/guide/contributions" onClick={(e)=>{e.preventDefault();nav("/guide/contributions");}}><i className="bi bi-geo-alt"/>My Contributions</a>
  </nav><button className="guide-drawer-logout" onClick={logout}><i className="bi bi-box-arrow-right"/> Logout</button></aside>
  <section className="guide-main" id="top"><header className="guide-topbar"><div className="guide-welcome"><h1>Hello, {user.name?.split(" ")[0]||"Guide"}!</h1><p>Manage your packages, places and traveller bookings.</p></div><div className="guide-top-art"><img src="/assets/user-hero-clean.jpg" alt="Mountains"/><span>Local knowledge<br/>creates better journeys</span></div><button className="guide-notification" onClick={()=>setShowNotifications(true)} title="Guide notifications"><i className="bi bi-bell-fill"/>{notifications.filter(x=>!x.read).length>0&&<b>{notifications.filter(x=>!x.read).length}</b>}</button><ThemeToggle compact /><div className="guide-user guide-user-button" role="button" tabIndex={0} onClick={()=>nav("/guide/profile")} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")nav("/guide/profile")}} title="Open profile">{user.avatarData?<img className="guide-avatar guide-avatar-image" src={user.avatarData} alt="Profile"/>:<div className="guide-avatar">{(user.name||"G").charAt(0)}</div>}<div><strong>{user.name||"Local Guide"}</strong><small>Local Guide</small></div></div></header>
   <div className="guide-content"><section className={`guide-verification-banner ${guideStatus.toLowerCase()}`}><div className="guide-verification-icon"><i className={`bi ${verified?"bi-patch-check-fill":guideStatus==="Rejected"?"bi-x-circle-fill":"bi-hourglass-split"}`}/></div><div><span className="guide-verification-label">LOCAL GUIDE VERIFICATION</span><h2>{guideStatus}</h2><p>{statusNote}</p>{(guideStatus==="Rejected" || guideStatus==="Changes Required") && <small className="guide-rejection-reason"><strong>Admin reason:</strong> {rejectionReason || "No additional reason was provided."}</small>}</div><span className={`guide-verification-badge ${guideStatus.toLowerCase().replace(/\s+/g,"-")}`}>{guideStatus}</span></section><section className="guide-stats"><Stat icon="bi-box" value={packages.length} label="Travel Packages"/><Stat icon="bi-calendar-check" value={placeAvailability.length} label="Guide Availability Dates"/><Stat icon="bi-people-fill" value={activeBookings} label="Bookings" warm/><Stat icon="bi-star-fill" value="4.8" label="Average Rating" purple/></section>
    {notice&&<div className="alert alert-success py-2">{notice}</div>}
    <section className="guide-card guide-packages" id="packages"><div className="guide-card-heading"><div><h2>My Travel Packages</h2><p className="guide-subtitle">Packages are available to travellers after you publish them.</p></div><button className="guide-create" disabled={!verified} onClick={()=>{setEditingPackage(null);setShowCreate(true)}} title={!verified?"Admin approval is required before creating packages":"Create a package"}><i className="bi bi-plus-lg"/>{verified?"Create Package":"Awaiting Approval"}</button></div>
      {!verified&&<div className="guide-locked-note"><i className="bi bi-lock-fill"/><span>Package management is locked until STG Admin approves your Local Guide verification. Your application status remains visible above.</span></div>}{packages.length?<div className="guide-package-grid">{packages.map(p=><GuidePackage key={p.id} item={p} onDelete={()=>{removeGuidePackage(p.id);refresh();}} onEdit={()=>{setEditingPackage(p);setShowCreate(true)}}/>)}</div>:<Empty text="You have not created a package yet." action={verified?"Create your first package":"Admin approval required"} onClick={()=>{if(verified)setShowCreate(true)}}/>} </section>
    <section className="guide-card" id="availability"><div className="guide-card-heading"><div><h2>Guide Availability</h2><p className="guide-subtitle">Set the cities and dates when you are available to guide travellers.</p></div><button className="guide-create" disabled={!verified} onClick={()=>setShowPlace(true)} title={!verified?"Admin approval is required before setting guide availability":"Add availability"}><i className="bi bi-plus-lg"/>{verified?"Add Date":"Awaiting Approval"}</button></div>
      {!verified&&<div className="guide-locked-note"><i className="bi bi-lock-fill"/><span>Traveller-facing Guide Availability stays hidden until your account is verified by STG Admin.</span></div>}{placeAvailability.length?<div className="availability-list">{[...placeAvailability].sort((a,b)=>a.date.localeCompare(b.date)).map(x=><div className="availability-row" key={x.id}><div><strong>{x.city||x.placeCity||"City"}</strong><small>{formatDate(x.date)}</small></div><span className="availability-open">Available</span><button onClick={async()=>{await removeGuideAvailability(x.id);refresh();}}><i className="bi bi-trash"/></button></div>)}</div>:<Empty text="No guide availability dates added yet." action={verified?"Add availability":"Admin approval required"} onClick={()=>{if(verified)setShowPlace(true)}}/>}</section>
    <section className="guide-card bookings-card" id="bookings"><div className="guide-card-heading"><div><span className="guide-section-kicker">TRAVELLER BOOKINGS</span><h2>My Bookings</h2><p className="guide-subtitle">Package bookings and customized Guide / Travel System requests are managed here.</p></div><a href="#bookings" className="guide-booking-anchor">{bookings.length} total</a></div>{bookings.length?<div className="booking-table"><div className="booking-head"><span>Traveller</span><span>Booking</span><span>Location & dates</span><span>Details</span><span>Status</span></div>{bookings.map(b=>{const isGuideRequest=b.bookingType==="guide_request";const statusClass=String(b.status||"Pending").toLowerCase().replace(/\s+/g,"-");return <div className={`booking-row ${isGuideRequest?"guide-request-booking":""} ${highlightBookingId===String(b.id)?"guide-booking-focus":""}`} id={`guide-booking-${b.id}`} key={b.id}><span className="traveller"><i className="bi bi-person-circle"/><span><strong>{b.travellerName||"Traveller"}</strong><small>{b.travellerEmail||""}</small></span></span><span><span className={`booking-type-badge ${isGuideRequest?"guide-request":"package"}`}>{isGuideRequest?"Guide / Travel System":"Package"}</span><strong className="booking-primary-text">{b.packageName||b.tripName||"Booking"}</strong></span><span><strong>{b.location||"Package booking"}</strong><small>{formatDate(b.startDate)} – {formatDate(b.endDate)}</small></span><span><strong>{b.days||0} days</strong><small>{isGuideRequest?(b.places||[]).map(p=>p.name).join(", ")||"Customized trip":"Traveller booking"}</small></span><span><em className={`booking-status ${statusClass}`}>{b.status||"Pending"}</em>{b.statusReason&&<small className="booking-status-reason">{b.statusReason}</small>}</span></div>})}</div>:<Empty text="No bookings or Guide / Travel System requests yet."/>}</section>
   </div>
  </section>
  {showCreate&&<CreatePackageModal user={user} destinations={destinations} initial={editingPackage} onClose={()=>{setShowCreate(false);setEditingPackage(null)}} onCreated={async(p)=>{try{if(editingPackage){const r=await fetch(`/api/guide/packages/${encodeURIComponent(editingPackage.id)}`,{method:"PUT",headers:{"Content-Type":"application/json",...authHeaders()},credentials:"include",body:JSON.stringify(p)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Could not update package");}else await createGuidePackage(p);await refresh();setShowCreate(false);setEditingPackage(null);setNotice(editingPackage?"Package updated. Traveller view is synchronized.":"Package published. Travellers can now see and book it.");setTimeout(()=>setNotice(""),3500)}catch(e){alert(e.message||"Could not save package.")}}}/>}
  {showNotifications&&<GuideNotificationsModal notifications={notifications} onClose={()=>setShowNotifications(false)} onOpenBooking={openBookingFromNotification} onRead={async id=>{await markNotificationRead(id);await refresh();}}/>}
  {showPlace&&<PlaceAvailabilityModal user={user} packages={packages} destinations={destinations} onClose={()=>setShowPlace(false)} onCreated={async(x)=>{try{await createGuideAvailability(x);await refresh();setShowPlace(false);setNotice("Guide availability saved for the selected city and date.");setTimeout(()=>setNotice(""),3500)}catch(e){alert(e.message||"Could not save availability.")}}}/>}
 </main>
}
function Stat({icon,value,label,warm,purple}){return <div className={`guide-stat ${warm?"warm":""} ${purple?"purple":""}`}><i className={`bi ${icon}`}/><div><strong>{value}</strong><span>{label}</span></div></div>}
function Empty({text,action,onClick}){return <div className="empty-state guide-empty"><i className="bi bi-compass"/><strong>{text}</strong>{action&&<button onClick={onClick}>{action}</button>}</div>}
function GuidePackage({item,onDelete,onEdit}){return <article className="guide-package"><div className="guide-package-image"><img src={item.image} alt={item.name}/><b>Active</b></div><div className="guide-package-body"><h3>{item.name}</h3><div className="package-meta"><span><i className="bi bi-calendar3"/>{formatDate(item.startDate)} – {formatDate(item.endDate)}</span><span><i className="bi bi-clock"/>{item.days} days</span></div><p>{item.description}</p><div className="guide-place-tags">{(item.places||[]).map(p=><span key={p.id}>{p.name}</span>)}</div><strong className="guide-price">₹ {Number(item.price).toLocaleString("en-IN")} <small>per person</small></strong><div className="package-actions"><button onClick={onDelete}>Delete</button><button onClick={onEdit}>Edit</button><button onClick={()=>alert(`${item.name}\n${formatDateTime(item.startDate,item.startTime)} – ${formatDateTime(item.endDate,item.endTime)}\n${item.days} days\nCities: ${(item.cities||[...new Set((item.places||[]).map(p=>p.city).filter(Boolean))]).join(", ")}\nPlaces: ${(item.places||[]).map(p=>p.name).join(", ")}\nTravelling: ${item.travelEnabled?(item.travelSystems||[]).join(", "):"Not provided"}\nCost with travel: ${item.travelEnabled&&item.travelPrice?"₹ "+Number(item.travelPrice).toLocaleString("en-IN"):"Not provided"}`)}>View</button></div></div></article>}
function GuideNotificationsModal({notifications,onClose,onOpenBooking,onRead}){
 return <div className="modal-backdrop-custom"><div className="guide-modal guide-notifications-modal"><button type="button" className="modal-close" onClick={onClose}>×</button><div className="notification-modal-head"><div><span className="guide-section-kicker">ACTIVITY CENTER</span><h2>Notifications</h2><p>Booking and account updates appear here.</p></div></div>{notifications.length?notifications.map(n=>{const bookingRelated=Boolean(n.bookingId||n.requestId);return <button type="button" className={`notification-row ${n.read?"read":"unread"} ${bookingRelated?"notification-booking":""}`} key={n.id} onClick={()=>bookingRelated?onOpenBooking(n):onRead(n.id)}><span className="notification-icon"><i className={`bi ${bookingRelated?"bi-calendar2-check":"bi-bell-fill"}`}/></span><span className="notification-copy">{n.message}<small>{new Date(n.createdAt).toLocaleString("en-IN")}</small></span>{bookingRelated&&<span className="notification-open">View in My Bookings <i className="bi bi-arrow-right"/></span>}</button>}):<div className="empty-state guide-empty"><i className="bi bi-bell"/><strong>No notifications</strong><span>New booking and account updates will appear here.</span></div>}</div></div>
}
function CreatePackageModal({user,destinations=[],initial=null,onClose,onCreated}){
 const today=new Date().toLocaleDateString("en-CA");
 const initialCities=[...new Set((initial?.places||[]).map(p=>p.city).filter(Boolean))];
 const [f,setF]=useState(initial?{...initial,places:initial.places||[],travelSystems:initial.travelSystems||[],travelEnabled:initial.travelEnabled!==false,sameAsAbove:initial.travelPrice==null||Number(initial.travelPrice)===Number(initial.price)}:{name:"",startDate:"",startTime:"",endDate:"",endTime:"",places:[],image:"",maxTravellers:"",price:"",travelEnabled:true,travelSystems:[],travelPrice:"",sameAsAbove:true,description:""});
 const [city,setCity]=useState(initialCities[0]||""); const [placeSearch,setPlaceSearch]=useState(""); const [availableCities,setAvailableCities]=useState([]); const [cityPlaces,setCityPlaces]=useState([]);
 const set=(k,v)=>setF(x=>({...x,[k]:v}));
 const days=daysBetween(f.startDate,f.endDate);
 useEffect(()=>{fetchPlaceMeta().then(m=>setAvailableCities(m.cities||[]))},[]);
 useEffect(()=>{if(!city){setCityPlaces([]);return;} fetchAllPlacesByCity(city).then(setCityPlaces)},[city]);
 const cityNames=availableCities.length?availableCities:[...new Set(destinations.map(p=>p.city).filter(Boolean))].sort();
 const filteredCityPlaces=cityPlaces.filter(p=>String(p.type||"").toLowerCase()!=="city").filter(p=>`${p.name} ${p.type||""}`.toLowerCase().includes(placeSearch.toLowerCase()));
 const toggle=p=>setF(x=>({...x,places:x.places.some(y=>String(y.id)===String(p.id))?x.places.filter(y=>String(y.id)!==String(p.id)):[...x.places,p]}));
 const toggleTravelSystem=t=>setF(x=>({...x,travelSystems:x.travelSystems.includes(t)?x.travelSystems.filter(y=>y!==t):[...x.travelSystems,t]}));
 const onImage=e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024)return alert("Package image must be 5MB or smaller.");const reader=new FileReader();reader.onload=()=>set("image",reader.result);reader.readAsDataURL(file)};
 const submit=e=>{e.preventDefault();if(!f.name||!f.startDate||!f.startTime||!f.endDate||!f.endTime||!f.price||!f.description||!f.places.length||days<1)return alert("Please complete the required package details and select at least one place.");if(f.endDate<f.startDate)return alert("End date must be on or after start date.");if(f.endDate===f.startDate&&f.endTime<=f.startTime)return alert("End time must be after the start time.");if(f.travelEnabled&&!f.travelSystems.length)return alert("Select at least one travelling system or turn off travelling availability.");const finalTravelPrice=f.travelEnabled?(f.sameAsAbove?Number(f.price):Number(f.travelPrice)):null;onCreated({...f,id:f.id||crypto.randomUUID(),guideEmail:user.email,guideName:user.name,guidePhone:user.phone||"",days,price:Number(f.price),maxTravellers:Number(f.maxTravellers)||null,travelEnabled:f.travelEnabled,travelSystems:f.travelEnabled?f.travelSystems:[],travelPrice:finalTravelPrice,createdAt:f.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()})};
 return <Modal title={initial?"Edit Travel Package":"Create Travel Package"} onClose={onClose}><form onSubmit={submit} className="create-package-form">
  <div className="field full"><label>Package Name <em>*</em></label><input value={f.name} onChange={e=>set("name",e.target.value)} placeholder="Enter package name (e.g., Explore Kerala)" required/></div>
  <div className="form-grid package-date-grid"><Field label="Start Date & Time" type="datetime-local" min={`${today}T00:00`} value={f.startDate&&f.startTime?`${f.startDate}T${f.startTime}:00`.slice(0,16):""} onChange={v=>{const [d,t]=String(v).split("T");setF(x=>({...x,startDate:d||"",startTime:t||""}))}} required/><Field label="End Date & Time" type="datetime-local" min={`${f.startDate||today}T${f.startTime||"00:00"}`} value={f.endDate&&f.endTime?`${f.endDate}T${f.endTime}:00`.slice(0,16):""} onChange={v=>{const [d,t]=String(v).split("T");setF(x=>({...x,endDate:d||"",endTime:t||""}))}} required/></div>
  <div className="calculated-days"><i className="bi bi-calendar-check"/> Number of Days: <strong>{days||"—"}</strong> <small>(calculated automatically)</small></div>
  <div className="package-place-section"><div className="field"><label>City of Package Places <em>*</em></label><select value={city} onChange={e=>{setCity(e.target.value);setPlaceSearch("")}} required><option value="">Search and select a city</option>{cityNames.map(c=><option value={c} key={c}>{c}</option>)}</select><small>Only cities represented by places in the STG catalogue are shown.</small></div><div className="field"><label>Search places in {city||"selected city"}</label><input value={placeSearch} onChange={e=>setPlaceSearch(e.target.value)} disabled={!city} placeholder={city?`Search ${city} places`:"Select a city first"}/></div><div className="city-place-picker">{city?filteredCityPlaces.filter(p=>!f.places.some(x=>String(x.id)===String(p.id))).map(p=><button type="button" className="city-place-option" key={p.id} onClick={()=>toggle(p)}><span>{p.name}</span><small>{p.type||"Place"}</small><i className="bi bi-plus-circle"/></button>):<span>Select a city to see its available STG places.</span>}{city&&filteredCityPlaces.length===0&&<span>No places from the STG catalogue match this search.</span>}</div><div className="selected-places-box"><strong>Selected Places ({f.places.length})</strong>{f.places.length?<div className="selected-place-list">{f.places.map(p=><button type="button" key={p.id} onClick={()=>toggle(p)}>{p.name}<i className="bi bi-x"/></button>)}</div>:<span>No places selected yet</span>}</div></div>
  <div className="form-grid package-cost-grid"><div className="field package-upload"><label>Package Image <em>*</em></label><label className="upload-box"><i className="bi bi-cloud-arrow-up"/><strong>Upload Package Image</strong><small>JPG, PNG (Max 5MB)</small><input type="file" accept="image/jpeg,image/png" onChange={onImage}/></label>{f.image&&<img className="package-upload-preview" src={f.image} alt="Preview"/>}</div><Field label="Max Travellers" type="number" min="1" value={f.maxTravellers||""} onChange={v=>set("maxTravellers",v)} required/><Field label="Approximate Cost (₹)" type="number" min="1" value={f.price} onChange={v=>set("price",v)} required/></div>
  <section className={`travel-options-panel ${!f.travelEnabled?"disabled":""}`}><div className="travel-options-heading"><div><h3><i className="bi bi-bus-front-fill"/> Travelling System Availability <small>(Optional)</small></h3><p>Specify transport options if available. You can also provide a separate price with transport.</p></div><label className="switch-row"><input type="checkbox" checked={f.travelEnabled} onChange={e=>set("travelEnabled",e.target.checked)}/><span className="switch"/> <b>Add travel options</b></label></div>{f.travelEnabled&&<div className="travel-options-body"><div><label className="travel-label">Select Travelling Systems</label><div className="travel-chips">{["Car","Bus","Train","Flight","Ferry","Other"].map(t=><button type="button" key={t} className={f.travelSystems.includes(t)?"travel-chip active":"travel-chip"} onClick={()=>toggleTravelSystem(t)}>{t}</button>)}</div></div><div className="travel-price-side"><label>Package Cost with Travel (₹)</label><input type="number" min="1" value={f.travelPrice||""} disabled={f.sameAsAbove} onChange={e=>set("travelPrice",e.target.value)} placeholder="Enter cost per person (with travel)"/><label className="same-cost"><input type="checkbox" checked={f.sameAsAbove} onChange={e=>set("sameAsAbove",e.target.checked)}/> Same as above (use approximate cost)</label></div></div>}</section>
  <div className="field full"><label>Description <em>*</em></label><textarea rows="4" maxLength="1000" value={f.description} onChange={e=>set("description",e.target.value)} placeholder="Describe the tour, itinerary, experiences, inclusions and what travellers will see."/><small className="char-count">{f.description.length}/1000</small></div>
  <div className="modal-actions"><button type="button" className="btn btn-outline-primary" onClick={onClose}>Cancel</button><button className="btn btn-primary">{initial?"Save Changes":"Create Package"}</button></div>
 </form></Modal>}
function Modal({title,onClose,children}){return <div className="modal-backdrop-custom"><div className="guide-modal"><button className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</div></div>}
function Field({label,value,onChange,type="text",required,min}){return <div className="field"><label>{label} {required&&<em>*</em>}</label><input type={type} min={min} value={value} onChange={e=>onChange(e.target.value)} required={required}/></div>}

function PlaceAvailabilityModal({user,packages=[],destinations=[],onClose,onCreated}){
 const today=new Date().toLocaleDateString("en-CA");
 const [city,setCity]=useState(""); const [date,setDate]=useState(""); const [cities,setCities]=useState([]);
 useEffect(()=>{fetchPlaceMeta().then(m=>setCities(Array.isArray(m.cities)?m.cities:[])).catch(()=>setCities([]))},[]);
 const conflict=city&&date&&packages.some(p=>{
   const packageCities=Array.isArray(p.cities)&&p.cities.length?p.cities:[...new Set((p.places||[]).map(x=>x.city).filter(Boolean))];
   return packageCities.some(c=>String(c).trim().toLowerCase()===city.trim().toLowerCase()) && p.startDate<=date && date<=p.endDate;
 });
 const submit=e=>{e.preventDefault();if(!city||!date)return alert("Please select a city and availability date.");if(conflict)return alert("You already have a package covering this city on the selected date.");onCreated({id:crypto.randomUUID(),guideEmail:user.email,guideName:user.name,guidePhone:user.phone||"",city,date});};
 return <Modal title="Add Guide Availability" onClose={onClose}><form onSubmit={submit} className="create-package-form"><div className="field full"><label>City <em>*</em></label><select value={city} onChange={e=>setCity(e.target.value)} required><option value="">Select a city</option>{cities.map(c=><option key={c} value={c}>{c}</option>)}</select><small>Only cities represented by places currently available in the STG database are shown.</small></div><div className="field full"><label>Available Date <em>*</em></label><input type="date" min={today} value={date} onChange={e=>setDate(e.target.value)} required/></div>{conflict&&<div className="alert alert-warning">You have a package covering this city on the selected date.</div>}<div className="modal-actions"><button type="button" className="btn btn-outline-primary" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={!!conflict}>Save Availability</button></div></form></Modal>
}

function GuideRequestsModal({requests,onClose,onRespond}){
 const [reasonId,setReasonId]=useState(""); const [reason,setReason]=useState(""); const pending=requests.filter(r=>r.status==="Pending");
 return <Modal title="Guide / Travel System Requests" onClose={onClose}><div className="guide-request-list">{pending.length?pending.map(r=><article className="guide-request-card" key={r.id}><div className="request-title"><strong>{r.travellerName}</strong><span>Pending</span></div><p><b>Trip:</b> {r.tripName||"Custom Trip"}</p><p><b>Location:</b> {r.location}</p><p><b>Dates:</b> {formatDate(r.startDate)} – {formatDate(r.endDate)}</p><p><b>Places:</b> {(r.places||[]).map(p=>p.name).join(", ")}</p>{r.requirements&&<p><b>Requirements:</b> {r.requirements}</p>}<div className="request-actions"><button className="btn btn-primary" onClick={()=>onRespond(r.id,"Accepted","")}>Accept</button><button className="btn btn-outline-danger" onClick={()=>{setReasonId(r.id);setReason("")}}>Reject</button></div>{reasonId===r.id&&<div className="reject-reason-box"><label>Reason for rejection <small>(optional)</small></label><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Tell the traveller why you are unavailable." rows="3"/><div><button className="btn btn-outline-secondary" onClick={()=>setReasonId("")}>Cancel</button><button className="btn btn-danger" onClick={()=>{onRespond(r.id,"Rejected",reason);setReasonId("")}}>Confirm Reject</button></div></div>}</article>):<Empty text="No pending guide requests."/>}</div></Modal>
}
