import React,{useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import {getUser,fetchGuideRequests,respondGuideRequest,formatDate} from "../utils";

export default function GuideRequests(){
 const user=getUser()||{};const nav=useNavigate();const [requests,setRequests]=useState([]);const [reasonId,setReasonId]=useState("");const [reason,setReason]=useState("");const [notice,setNotice]=useState("");
 const refresh=async()=>setRequests(await fetchGuideRequests({guideEmail:user.email}));
 useEffect(()=>{refresh();const t=setInterval(refresh,5000);return()=>clearInterval(t)},[]);
 const respond=async(id,status)=>{try{await respondGuideRequest(id,status,status==="Rejected"?reason:"");setReasonId("");setReason("");setNotice(status==="Accepted"?"Request accepted. The traveller has been notified.":"Request rejected. The traveller has been notified.");await refresh();setTimeout(()=>setNotice(""),3500)}catch(e){alert(e.message||"Could not update request.")}};
 return <main className="inner-page guide-requests-page"><div className="inner-header"><button className="btn btn-outline-primary mb-3" onClick={()=>nav("/guide")}><i className="bi bi-arrow-left"/> Back to Dashboard</button><span className="eyebrow"><i className="bi bi-bell-fill"/> Guide requests</span><h1>Guide / Travel System Requests</h1><p>Review traveller trip details and requirements, then accept or reject each request.</p></div>{notice&&<div className="alert alert-success">{notice}</div>}<div className="guide-request-page-list">{requests.length?requests.map(r=><article className={`guide-request-card ${r.status.toLowerCase()}`} key={r.id}><div className="request-title"><div><strong>{r.travellerName}</strong><small>{r.travellerEmail}</small></div><span>{r.status}</span></div><div className="request-detail-grid"><p><b>Trip:</b> {r.tripName||"Custom Trip"}</p><p><b>Location:</b> {r.location}</p><p><b>Dates:</b> {formatDate(r.startDate)} – {formatDate(r.endDate)}</p><p><b>Places:</b> {(r.places||[]).map(p=>p.name).join(", ")}</p></div>{r.requirements&&<div className="request-requirements"><b>Traveller Requirements</b><p>{r.requirements}</p></div>}{r.status==="Pending"?<div className="request-actions"><button className="btn btn-primary" onClick={()=>respond(r.id,"Accepted")}>Accept</button><button className="btn btn-outline-danger" onClick={()=>{setReasonId(r.id);setReason("")}}>Reject</button></div>:r.status==="Rejected"&&r.rejectionReason?<p className="request-rejection"><b>Rejection reason:</b> {r.rejectionReason}</p>:r.status==="Accepted"?<p className="request-accepted"><i className="bi bi-check-circle-fill"/> Accepted — traveller can now see your contact details.</p>:r.status==="Not Available"?<p className="request-not-available"><i className="bi bi-calendar-x-fill"/> Not Available — this request was cancelled because the required availability is no longer active.</p>:null}{reasonId===r.id&&<div className="reject-reason-box"><label>Reason for rejection <small>(optional)</small></label><textarea value={reason} onChange={e=>setReason(e.target.value)} rows="3" placeholder="Tell the traveller why you are unavailable."/><div><button className="btn btn-outline-secondary" onClick={()=>setReasonId("")}>Cancel</button><button className="btn btn-danger" onClick={()=>respond(r.id,"Rejected")}>Confirm Reject</button></div></div>}</article>):<div className="empty-state"><i className="bi bi-bell"/><strong>No guide requests yet</strong><span>New traveller requests will appear here.</span></div>}</div></main>;
}
