import React, { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../utils";

const emptyForm = { placeName:"", city:"", state:"", category:"Tourist Place", address:"", imageUrl:"", description:"" };
const STATUS_TABS = [["all","All"],["Pending","Pending"],["Approved","Approved"],["Needs Correction","Needs Correction"],["Rejected","Rejected"]];

export default function MyContributions(){
 const [form,setForm]=useState(emptyForm),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[showForm,setShowForm]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await apiFetch("/api/place-submissions/mine");const d=await r.json();if(!r.ok)throw new Error(d.message||"Could not load contributions.");setItems(Array.isArray(d)?d:[]);}catch(e){setError(e.message||"Could not load contributions.");}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,5000);window.addEventListener("focus",load);return()=>{clearInterval(t);window.removeEventListener("focus",load)}},[]);
 const set=(name,value)=>setForm(x=>({...x,[name]:value}));
 async function submit(e){e.preventDefault();setSaving(true);setError("");setNotice("");try{const r=await apiFetch("/api/place-submissions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Could not submit the place.");setNotice("Your place contribution was submitted for Admin verification.");setForm(emptyForm);setShowForm(false);await load();setTimeout(()=>setNotice(""),4000)}catch(e){setError(e.message||"Could not submit the place.");}finally{setSaving(false)}}
 const counts=useMemo(()=>({all:items.length,pending:items.filter(x=>["pending","under review"].includes(String(x.status||"").toLowerCase())).length,approved:items.filter(x=>String(x.status||"").toLowerCase()==="approved").length,correction:items.filter(x=>String(x.status||"").toLowerCase()==="needs correction").length,rejected:items.filter(x=>String(x.status||"").toLowerCase()==="rejected").length}),[items]);
 const visibleItems=useMemo(()=>items.filter(item=>{if(filter==="all")return true;if(filter==="Pending")return ["pending","under review"].includes(String(item.status||"").toLowerCase());return String(item.status||"").toLowerCase()===filter.toLowerCase()}),[items,filter]);
 return <main className="inner-page contributions-page professional-contributions">
  <div className="inner-header contribution-page-header"><div><span className="eyebrow"><i className="bi bi-geo-alt-fill"/> Contribution Tracker</span><h1>My Contributions</h1><p>Track the places you submit, review Admin decisions, and see exactly what needs attention.</p></div><button type="button" className="contribution-primary-action" onClick={()=>setShowForm(v=>!v)}><i className={`bi ${showForm?"bi-x-lg":"bi-plus-lg"}`}/>{showForm?"Close Submission Form":"Add a New Place"}</button></div>
  {notice&&<div className="contribution-alert success"><i className="bi bi-check-circle-fill"/>{notice}</div>}
  {error&&<div className="contribution-alert error"><i className="bi bi-exclamation-triangle-fill"/><span>{error}</span><button type="button" onClick={()=>setError("")} aria-label="Dismiss">×</button></div>}
  <section className="contribution-summary"><StatusStat label="Total" value={counts.all} tone="all" icon="bi-collection"/><StatusStat label="Pending" value={counts.pending} tone="pending" icon="bi-hourglass-split"/><StatusStat label="Approved" value={counts.approved} tone="approved" icon="bi-check2-circle"/><StatusStat label="Needs Correction" value={counts.correction} tone="correction" icon="bi-pencil-square"/><StatusStat label="Rejected" value={counts.rejected} tone="rejected" icon="bi-x-circle"/></section>
  {showForm&&<section className="contribution-form-card module-reference-form"><div className="contribution-card-head module-reference-heading"><div><span className="contribution-module-label">MODULE 05 / PLACE MANAGEMENT</span><h2>Add Your Place</h2><p>Provide complete information so the STG Admin team can verify your submission efficiently.</p></div><span className="contribution-section-number">01</span></div><form onSubmit={submit}><div className="contribution-section-block"><SectionTitle number="01" title="Basic Information" subtitle="Tell travellers about the place"/><div className="form-grid"><Field label="Place Name" value={form.placeName} onChange={v=>set("placeName",v)} placeholder="Example: Araku Valley" required full/><div className="field"><label>Category <em>*</em></label><select value={form.category} onChange={e=>set("category",e.target.value)} required><option>Tourist Place</option><option>Historical</option><option>Mountains</option><option>Nature</option><option>Beaches</option><option>Culture</option><option>Spiritual</option><option>Adventure</option></select></div><Field label="City" value={form.city} onChange={v=>set("city",v)} placeholder="City" required/><Field label="State" value={form.state} onChange={v=>set("state",v)} placeholder="State" required/></div></div><div className="contribution-section-block"><SectionTitle number="02" title="Location & Media" subtitle="Help travellers identify the place"/><div className="form-grid"><Field label="Address" value={form.address} onChange={v=>set("address",v)} placeholder="Full address" required full/><Field label="Image URL" value={form.imageUrl} onChange={v=>set("imageUrl",v)} type="url" placeholder="https://..." required full/></div></div><div className="contribution-section-block"><SectionTitle number="03" title="Description" subtitle="Describe the experience"/><div className="field"><textarea rows="5" required value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Describe the place, what travellers can experience and why it should be added to STG."/></div></div><div className="contribution-form-actions"><button type="button" className="btn btn-outline-primary" onClick={()=>setShowForm(false)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?<><span className="spinner-border spinner-border-sm me-2"/>Submitting…</>:<>Submit for Verification <i className="bi bi-arrow-right"/></>}</button></div></form></section>}
  <section className="contribution-history-card"><div className="contribution-history-head"><div><span className="contribution-module-label">CONTRIBUTION TRACKER</span><h2>My Submissions</h2><p>Every submitted place stays here with its current verification status and Admin feedback.</p></div><span className="submission-count">{visibleItems.length} shown</span></div><div className="contribution-filter-bar">{STATUS_TABS.map(([key,label])=><button type="button" key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{label}<b>{key==="all"?counts.all:key==="Pending"?counts.pending:key==="Approved"?counts.approved:key==="Needs Correction"?counts.correction:counts.rejected}</b></button>)}</div>{loading?<div className="place-loading compact-loading"><div className="spinner-border text-primary"/><span>Loading contributions…</span></div>:visibleItems.length?<div className="professional-submission-list">{visibleItems.map(item=><ContributionRow key={item.id} item={item}/>)}</div>:<div className="empty-state contribution-empty professional-empty"><i className="bi bi-inbox"/><strong>{filter==="all"?"No contributions yet.":`No ${filter.toLowerCase()} contributions.`}</strong><span>{filter==="all"?"Your submitted places will appear here with their verification history.":"Try another status filter or submit a new place."}</span>{filter!=="all"&&<button type="button" onClick={()=>setFilter("all")}>View All</button>}</div>}</section>
 </main>;
}
function SectionTitle({number,title,subtitle}){return <div className="contribution-section-title"><span>{number}</span><div><h3>{title}</h3><p>{subtitle}</p></div></div>}
function Field({label,value,onChange,type="text",required=false,placeholder="",full=false}){return <div className={`field ${full?"full":""}`}><label>{label}{required&&<em> *</em>}</label><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} required={required}/></div>}
function StatusStat({label,value,tone,icon}){return <div className={`contribution-stat ${tone}`}><span className="contribution-stat-icon"><i className={`bi ${icon}`}/></span><div><strong>{value}</strong><span>{label}</span></div></div>}
function ContributionRow({item}){const status=String(item.status||"Pending");const tone=status.toLowerCase().replace(/\s+/g,"-");const history=Array.isArray(item.history)?item.history:[];const feedback=item.reason||"";return <article className="professional-submission-card"><div className="submission-card-main"><div className="submission-card-kicker"><span>{item.category||"PLACE CONTRIBUTION"}</span><time>{item.submittedAt?new Date(item.submittedAt).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—"}</time></div><div className="submission-card-title-row"><div><h3>{item.placeName||"Place"}</h3><p><i className="bi bi-geo-alt"/> {item.city||""}{item.state?`, ${item.state}`:""}</p></div><span className={`professional-status ${tone}`}><i className={`bi ${tone==="approved"?"bi-check-circle-fill":tone==="rejected"?"bi-x-circle-fill":tone==="needs-correction"?"bi-pencil-square":"bi-hourglass-split"}`}/>{status}</span></div><p className="submission-description">{item.description||"No description provided."}</p>{feedback&&<div className={`submission-feedback ${status.toLowerCase()==="needs correction"?"correction":"rejected"}`}><strong><i className="bi bi-chat-left-text-fill"/> Admin Feedback</strong><p>{feedback}</p></div>}<div className="submission-timeline"><strong>Verification history</strong><div className="timeline-items">{history.length?history.slice(0,5).map((h,i)=><div className={`timeline-item ${i===0?"current":""}`} key={`${h.status}-${h.at}-${i}`}><span className="timeline-dot"/><div><b>{h.status}</b><small>{h.at?new Date(h.at).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—"}{h.note?` · ${h.note}`:""}</small></div></div>):<div className="timeline-item current"><span className="timeline-dot"/><div><b>{status}</b><small>Current status</small></div></div>}</div></div></div></article>}
